FROM node
RUN mkdir -p /root/Major_Project
ADD /root/training-project/Team7_React/Major_Project /root/Major_Project
WORKDIR /root/Major_Project/expressdine-client/
RUN npm install react
RUN npm start

