version: '3'
services:
     node:
             container_name: node
             build: .
             #volumes:
             #        - ./Team7_React/Major_Project/expressdine-client:/root/expressdine-client
             ports:
                     - 3333:3000
     mysqld:
             container_name: mysql
             image: mysql:8
             environment:
                     - MYSQL_ROOT_PASSWORD=password
                     - MYSQL_DATABASE=expressdine
                     - MYSQL_USER=admin
                     - MYSQL_PASSWORD=admin
             ports:
                     - 3310:3306

